
package Lab6P2_JafetHou;

import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class Lab6P2_JafetHou extends javax.swing.JFrame {

    
    public Lab6P2_JafetHou() {
        
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_CrearEquipo = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jt_CiudadEquipo = new javax.swing.JTextField();
        jt_PaisEquipo = new javax.swing.JTextField();
        jt_NombreEquipo = new javax.swing.JTextField();
        jb_AgregarEquipo = new javax.swing.JButton();
        jb_RegresarEquipo = new javax.swing.JButton();
        jt_EstadioEquipo = new javax.swing.JTextField();
        jd_CrearJugador = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jt_NombreJug1 = new javax.swing.JTextField();
        js_EdadJug = new javax.swing.JSpinner();
        jc_PosicionJug = new javax.swing.JComboBox<>();
        jb_AgregarJug = new javax.swing.JButton();
        jb_RegresarJug = new javax.swing.JButton();
        jd_Transferencia = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlist_Jugadores = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtree_Equipos = new javax.swing.JTree();
        jb_Transferir = new javax.swing.JButton();
        jb_RegresarTransferir = new javax.swing.JButton();
        jpp_modificar = new javax.swing.JPopupMenu();
        jm_Modificar = new javax.swing.JMenuItem();
        jpp_Eliminar = new javax.swing.JPopupMenu();
        jm_Eliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jb_CrearEquipo = new javax.swing.JButton();
        jb_CrearJug = new javax.swing.JButton();
        jb_Transferencia = new javax.swing.JButton();
        jb_Salir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jm_CrearEquipo = new javax.swing.JMenuItem();
        jm_CrearJug = new javax.swing.JMenuItem();
        jm_Transferencia = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Crear Equipo");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 240, -1));

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ciudad");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Pais del Equipo");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre del Equipo");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Estadio");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jt_CiudadEquipo.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jt_CiudadEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 200, -1));

        jt_PaisEquipo.setBackground(new java.awt.Color(255, 255, 255));
        jt_PaisEquipo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jt_PaisEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 200, -1));

        jt_NombreEquipo.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jt_NombreEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 200, -1));

        jb_AgregarEquipo.setBackground(new java.awt.Color(255, 255, 255));
        jb_AgregarEquipo.setForeground(new java.awt.Color(0, 0, 0));
        jb_AgregarEquipo.setText("Agregar");
        jb_AgregarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_AgregarEquipoMouseClicked(evt);
            }
        });
        jPanel2.add(jb_AgregarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 90, 40));

        jb_RegresarEquipo.setBackground(new java.awt.Color(255, 255, 255));
        jb_RegresarEquipo.setForeground(new java.awt.Color(0, 0, 0));
        jb_RegresarEquipo.setText("Regresar");
        jb_RegresarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_RegresarEquipoMouseClicked(evt);
            }
        });
        jPanel2.add(jb_RegresarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 80, 40));

        jt_EstadioEquipo.setBackground(new java.awt.Color(255, 255, 255));
        jt_EstadioEquipo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jt_EstadioEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 200, -1));

        javax.swing.GroupLayout jd_CrearEquipoLayout = new javax.swing.GroupLayout(jd_CrearEquipo.getContentPane());
        jd_CrearEquipo.getContentPane().setLayout(jd_CrearEquipoLayout);
        jd_CrearEquipoLayout.setHorizontalGroup(
            jd_CrearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
        jd_CrearEquipoLayout.setVerticalGroup(
            jd_CrearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setForeground(new java.awt.Color(255, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Crear Jugador");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 240, -1));

        jLabel8.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Edad");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Posicion");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel10.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nombre");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jt_NombreJug1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jt_NombreJug1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 150, -1));

        js_EdadJug.setModel(new javax.swing.SpinnerNumberModel(15, 15, 45, 1));
        jPanel3.add(js_EdadJug, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 150, 30));

        jc_PosicionJug.setBackground(new java.awt.Color(255, 255, 255));
        jc_PosicionJug.setForeground(new java.awt.Color(0, 0, 0));
        jc_PosicionJug.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delantero", "Centrocampista", "Defensa", "Portero", " " }));
        jPanel3.add(jc_PosicionJug, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 150, 30));

        jb_AgregarJug.setBackground(new java.awt.Color(255, 255, 255));
        jb_AgregarJug.setForeground(new java.awt.Color(0, 0, 0));
        jb_AgregarJug.setText("Agregar");
        jb_AgregarJug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_AgregarJugMouseClicked(evt);
            }
        });
        jPanel3.add(jb_AgregarJug, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 100, 40));

        jb_RegresarJug.setBackground(new java.awt.Color(255, 255, 255));
        jb_RegresarJug.setForeground(new java.awt.Color(0, 0, 0));
        jb_RegresarJug.setText("Regresar");
        jb_RegresarJug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_RegresarJugMouseClicked(evt);
            }
        });
        jPanel3.add(jb_RegresarJug, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 90, 40));

        javax.swing.GroupLayout jd_CrearJugadorLayout = new javax.swing.GroupLayout(jd_CrearJugador.getContentPane());
        jd_CrearJugador.getContentPane().setLayout(jd_CrearJugadorLayout);
        jd_CrearJugadorLayout.setHorizontalGroup(
            jd_CrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );
        jd_CrearJugadorLayout.setVerticalGroup(
            jd_CrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Transferencia");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 250, 70));

        jLabel12.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Equipos");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        jLabel13.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Jugadores");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jlist_Jugadores.setBackground(new java.awt.Color(255, 255, 255));
        jlist_Jugadores.setForeground(new java.awt.Color(0, 0, 0));
        jlist_Jugadores.setModel(new DefaultListModel()
        );
        jlist_Jugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlist_JugadoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jlist_Jugadores);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 200, 280));

        jtree_Equipos.setBackground(new java.awt.Color(255, 255, 255));
        jtree_Equipos.setForeground(new java.awt.Color(0, 0, 0));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jtree_Equipos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jtree_Equipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtree_EquiposMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtree_Equipos);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 220, 280));

        jb_Transferir.setBackground(new java.awt.Color(255, 255, 255));
        jb_Transferir.setForeground(new java.awt.Color(0, 0, 0));
        jb_Transferir.setText("Transferir ->");
        jb_Transferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_TransferirActionPerformed(evt);
            }
        });
        jPanel4.add(jb_Transferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        jb_RegresarTransferir.setBackground(new java.awt.Color(255, 255, 255));
        jb_RegresarTransferir.setForeground(new java.awt.Color(0, 0, 0));
        jb_RegresarTransferir.setText("Regresar");
        jb_RegresarTransferir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_RegresarTransferirMouseClicked(evt);
            }
        });
        jPanel4.add(jb_RegresarTransferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        javax.swing.GroupLayout jd_TransferenciaLayout = new javax.swing.GroupLayout(jd_Transferencia.getContentPane());
        jd_Transferencia.getContentPane().setLayout(jd_TransferenciaLayout);
        jd_TransferenciaLayout.setHorizontalGroup(
            jd_TransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
        );
        jd_TransferenciaLayout.setVerticalGroup(
            jd_TransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        jm_Modificar.setText("Modificar");
        jm_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_ModificarActionPerformed(evt);
            }
        });
        jpp_modificar.add(jm_Modificar);

        jm_Eliminar.setText("ELIMINAR");
        jpp_Eliminar.add(jm_Eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bienvenido a Boroa League");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 400, 50));

        jToolBar1.setBackground(new java.awt.Color(153, 204, 255));
        jToolBar1.setRollover(true);

        jb_CrearEquipo.setBackground(new java.awt.Color(153, 204, 255));
        jb_CrearEquipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jb_CrearEquipo.setForeground(new java.awt.Color(0, 0, 0));
        jb_CrearEquipo.setText("Crear Equipo");
        jb_CrearEquipo.setFocusable(false);
        jb_CrearEquipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_CrearEquipo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jb_CrearEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CrearEquipoMouseClicked(evt);
            }
        });
        jToolBar1.add(jb_CrearEquipo);

        jb_CrearJug.setBackground(new java.awt.Color(153, 204, 255));
        jb_CrearJug.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jb_CrearJug.setForeground(new java.awt.Color(0, 0, 0));
        jb_CrearJug.setText("Crear Jugadores");
        jb_CrearJug.setFocusable(false);
        jb_CrearJug.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_CrearJug.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jb_CrearJug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CrearJugMouseClicked(evt);
            }
        });
        jToolBar1.add(jb_CrearJug);

        jb_Transferencia.setBackground(new java.awt.Color(153, 204, 255));
        jb_Transferencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jb_Transferencia.setForeground(new java.awt.Color(0, 0, 0));
        jb_Transferencia.setText("Transferencia");
        jb_Transferencia.setFocusable(false);
        jb_Transferencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_Transferencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jb_Transferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_TransferenciaMouseClicked(evt);
            }
        });
        jToolBar1.add(jb_Transferencia);

        jPanel1.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 40));

        jb_Salir.setBackground(new java.awt.Color(255, 255, 255));
        jb_Salir.setForeground(new java.awt.Color(0, 0, 0));
        jb_Salir.setText("Salir");
        jb_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_SalirMouseClicked(evt);
            }
        });
        jPanel1.add(jb_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 90, 30));

        jMenu1.setText("Opciones");

        jm_CrearEquipo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jm_CrearEquipo.setText("Crear Equipos");
        jm_CrearEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_CrearEquipoMouseClicked(evt);
            }
        });
        jMenu1.add(jm_CrearEquipo);

        jm_CrearJug.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jm_CrearJug.setText("Crear Jugadores");
        jMenu1.add(jm_CrearJug);

        jm_Transferencia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jm_Transferencia.setText("Transferencia");
        jMenu1.add(jm_Transferencia);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_CrearEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CrearEquipoMouseClicked
        
        this.setVisible(false);
        jd_CrearEquipo.setModal(true);
        jd_CrearEquipo.pack();
        jd_CrearEquipo.setResizable(false);
        jd_CrearEquipo.setLocationRelativeTo(null);
        jd_CrearEquipo.setVisible(true);
        
    }//GEN-LAST:event_jb_CrearEquipoMouseClicked

    private void jm_CrearEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_CrearEquipoMouseClicked
        this.setVisible(false);
        jd_CrearEquipo.setModal(true);
        jd_CrearEquipo.pack();
        jd_CrearEquipo.setResizable(false);
        jd_CrearEquipo.setLocationRelativeTo(null);
        jd_CrearEquipo.setVisible(true);
    }//GEN-LAST:event_jm_CrearEquipoMouseClicked

    private void jb_AgregarEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_AgregarEquipoMouseClicked
        
        if(jt_NombreEquipo.getText().equals("") ){
            
            JOptionPane.showMessageDialog(null, "Ingrese nombre al Equipo");
            
        }else if(jt_PaisEquipo.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "Ingrese pais al Equipo");
            
        }else if(jt_CiudadEquipo.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "Ingrese ciudad al Equipo");
            
        }else if(jt_EstadioEquipo.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "Ingrese estadio al Equipo");
            
        }else{    
            
            DefaultTreeModel m = (DefaultTreeModel) jtree_Equipos.getModel();

            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();

            DefaultMutableTreeNode nodo_Equipos;
            nodo_Equipos = new DefaultMutableTreeNode(new Equipo(jt_NombreEquipo.getText()));

            DefaultMutableTreeNode pais;
            pais = new DefaultMutableTreeNode(jt_PaisEquipo.getText());

            DefaultMutableTreeNode posicion;
            posicion = new DefaultMutableTreeNode((String) jc_PosicionJug.getSelectedItem());


            DefaultMutableTreeNode jugador;
            jugador = new DefaultMutableTreeNode(jt_NombreJug1.getText());

            posicion.add(jugador);
            nodo_Equipos.add(posicion);
            pais.add(nodo_Equipos);
            raiz.add(pais);
            m.reload();
        
            jt_PaisEquipo.setText("");
            jt_NombreEquipo.setText("");
            jt_CiudadEquipo.setText("");
            jt_EstadioEquipo.setText("");
        }
    }//GEN-LAST:event_jb_AgregarEquipoMouseClicked

    private void jb_TransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_TransferirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_TransferirActionPerformed

    private void jb_CrearJugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CrearJugMouseClicked
        this.setVisible(false);
        jd_CrearJugador.setModal(true);
        jd_CrearJugador.pack();
        jd_CrearJugador.setResizable(false);
        jd_CrearJugador.setLocationRelativeTo(null);
        jd_CrearJugador.setVisible(true);
    }//GEN-LAST:event_jb_CrearJugMouseClicked

    private void jb_RegresarEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_RegresarEquipoMouseClicked
        jd_CrearEquipo.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jb_RegresarEquipoMouseClicked

    private void jb_RegresarTransferirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_RegresarTransferirMouseClicked
        jd_Transferencia.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jb_RegresarTransferirMouseClicked

    private void jb_RegresarJugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_RegresarJugMouseClicked
        jd_CrearJugador.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jb_RegresarJugMouseClicked

    private void jb_TransferenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_TransferenciaMouseClicked
        this.setVisible(false);
        jd_Transferencia.setModal(true);
        jd_Transferencia.pack();
        jd_Transferencia.setResizable(false);
        jd_Transferencia.setLocationRelativeTo(null);
        jd_Transferencia.setVisible(true);
    }//GEN-LAST:event_jb_TransferenciaMouseClicked

    private void jb_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jb_SalirMouseClicked

    private void jtree_EquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtree_EquiposMouseClicked
        if(evt.getButton() == 3){
            int row = jtree_Equipos.getClosestRowForLocation(evt.getX(), evt.getY());
            
            jtree_Equipos.setSelectionRow(row);
            
            Object c2 = jtree_Equipos.getSelectionPath().getLastPathComponent();
            
            nodo_selec = (DefaultMutableTreeNode)c2;
            
            if(nodo_selec.getUserObject() instanceof Equipo){
                Equipo_Selec = (Equipo) nodo_selec.getUserObject();
                
                jpp_Eliminar.show(evt.getComponent(), evt.getX(), evt.getY());
                
            }else if(nodo_selec.getUserObject() instanceof Jugadores){
                
                jug_sele = (Jugadores) nodo_selec.getUserObject();
                
                jpp_modificar.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jtree_EquiposMouseClicked

    private void jb_AgregarJugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_AgregarJugMouseClicked
        
        if(jt_NombreJug1.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "Ingrese nombre del Jugador");
            
        }else{
            DefaultListModel model = (DefaultListModel) jlist_Jugadores.getModel();

            model.addElement(new Jugadores(jt_NombreJug1.getText(), (String)jc_PosicionJug.getSelectedItem(), (Integer) js_EdadJug.getValue()));

            jlist_Jugadores.setModel(model);
            jt_NombreJug1.setText("");
            js_EdadJug.setValue(15);
            jc_PosicionJug.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jb_AgregarJugMouseClicked

    private void jlist_JugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlist_JugadoresMouseClicked
        if(jlist_Jugadores.getSelectedIndex() >= 0){
            if(evt.isMetaDown()){
                jpp_modificar.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jlist_JugadoresMouseClicked

    private void jm_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_ModificarActionPerformed
        if(jlist_Jugadores.getSelectedIndex() >= 0){
            
            DefaultListModel modelista = (DefaultListModel) jlist_Jugadores.getModel();
            
            ((Jugadores) modelista.get(jlist_Jugadores.getSelectedIndex())).setNombre(JOptionPane.showInputDialog("Ingrese nuevo nombre: "));
            
            ((Jugadores) modelista.get(jlist_Jugadores.getSelectedIndex())).setEdad(Integer.parseInt(JOptionPane.showInputDialog("Ingrese nueva edad: ")));
            
            jlist_Jugadores.setModel(modelista); 
        }
    }//GEN-LAST:event_jm_ModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab6P2_JafetHou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab6P2_JafetHou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab6P2_JafetHou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab6P2_JafetHou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab6P2_JafetHou().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jb_AgregarEquipo;
    private javax.swing.JButton jb_AgregarJug;
    private javax.swing.JButton jb_CrearEquipo;
    private javax.swing.JButton jb_CrearJug;
    private javax.swing.JButton jb_RegresarEquipo;
    private javax.swing.JButton jb_RegresarJug;
    private javax.swing.JButton jb_RegresarTransferir;
    private javax.swing.JButton jb_Salir;
    private javax.swing.JButton jb_Transferencia;
    private javax.swing.JButton jb_Transferir;
    private javax.swing.JComboBox<String> jc_PosicionJug;
    private javax.swing.JDialog jd_CrearEquipo;
    private javax.swing.JDialog jd_CrearJugador;
    private javax.swing.JDialog jd_Transferencia;
    private javax.swing.JList<String> jlist_Jugadores;
    private javax.swing.JMenuItem jm_CrearEquipo;
    private javax.swing.JMenuItem jm_CrearJug;
    private javax.swing.JMenuItem jm_Eliminar;
    private javax.swing.JMenuItem jm_Modificar;
    private javax.swing.JMenuItem jm_Transferencia;
    private javax.swing.JPopupMenu jpp_Eliminar;
    private javax.swing.JPopupMenu jpp_modificar;
    private javax.swing.JSpinner js_EdadJug;
    private javax.swing.JTextField jt_CiudadEquipo;
    private javax.swing.JTextField jt_EstadioEquipo;
    private javax.swing.JTextField jt_NombreEquipo;
    private javax.swing.JTextField jt_NombreJug1;
    private javax.swing.JTextField jt_PaisEquipo;
    private javax.swing.JTree jtree_Equipos;
    // End of variables declaration//GEN-END:variables
    DefaultMutableTreeNode nodo_selec;
    Jugadores jug_sele;
    Equipo Equipo_Selec;
}
